[workspace]
resolver = "3"
members = [
    "crates/domain",
    "crates/ports",
    "crates/application",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[workspace.dependencies]
uuid = { version = "1", features = ["v7"] }
