apiVersion: v1
kind: Service
metadata:
  name: {{ include "ferrobox.fullname" . }}
  labels:
    {{- include "ferrobox.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "ferrobox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
