//! Detection of OCI signature accessories (Cosign / Sigstore, Notation)
//! and attestations (DSSE / in-toto).
//!
//! Cosign can attach the signature in two ways:
//!
//! * classic `sha256-<digest>.sig` tag on the same image name;
//! * manifest with `subject` and the [Referrers API](https://github.com/opencontainers/distribution-spec)
//!   (`GET /v2/<name>/referrers/<digest>`).
//!
//! Besides detection, it can verify a Cosign *simple
//! signing* signature against PEM public keys (those generated by
//! `cosign generate-key-pair`). It does not cover keyless / Fulcio.

use base64::Engine;
use base64::engine::general_purpose::{STANDARD, URL_SAFE, URL_SAFE_NO_PAD};
use p256::ecdsa::signature::Verifier;
use p256::ecdsa::{Signature, VerifyingKey};
use p256::pkcs8::DecodePublicKey;

/// Media type of a Cosign simple-signing payload.
pub const COSIGN_SIMPLE_MEDIA_TYPE: &str = "application/vnd.dev.cosign.simplesigning.v1+json";

/// Cosign annotation that stores the signature in Base64.
pub const COSIGN_SIGNATURE_ANNOTATION: &str = "dev.cosignproject.cosign/signature";

/// Simple signature extracted from a Cosign manifest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SimpleSignature {
    /// Digest of the payload blob (`sha256:…`).
    pub payload_digest: String,
    /// Base64 signature (Cosign annotation).
    pub signature_b64: String,
}

/// Media type of a DSSE envelope (Cosign attestations).
pub const DSSE_ENVELOPE_MEDIA_TYPE: &str = "application/vnd.dsse.envelope.v1+json";

/// Media type of a Notation / Notary signature.
pub const NOTATION_MEDIA_TYPE: &str = "application/vnd.cncf.notary.signature";

/// Class of OCI accessory associated with an artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AccessoryKind {
    /// Cosign / Sigstore / Notation signature.
    Signature,
    /// Attestation (DSSE, in-toto).
    Attestation,
    /// Other referrer (attached SBOM, etc.).
    Other,
}

impl AccessoryKind {
    /// Label persisted on the index entry.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Signature => "signature",
            Self::Attestation => "attestation",
            Self::Other => "other",
        }
    }

    /// Rebuilds the class from the persisted label.
    #[must_use]
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "signature" => Some(Self::Signature),
            "attestation" => Some(Self::Attestation),
            "other" => Some(Self::Other),
            _ => None,
        }
    }
}

/// Accessory metadata extracted from an OCI manifest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AccessoryMeta {
    /// Detected class. `None` if the manifest is a normal image.
    pub kind: Option<AccessoryKind>,
    /// `sha256:…` digest of the subject artifact, if known.
    pub subject: Option<String>,
    /// OCI `artifactType`, if the manifest or layers declare it.
    pub artifact_type: Option<String>,
}

/// Inspects a published manifest and decides whether it is an accessory.
#[must_use]
pub fn inspect(reference: &str, media_type: &str, body: &[u8]) -> AccessoryMeta {
    let parsed = serde_json::from_slice::<serde_json::Value>(body).ok();
    let subject = parsed
        .as_ref()
        .and_then(subject_from_manifest)
        .or_else(|| subject_from_tag(reference));
    let artifact_type = parsed.as_ref().and_then(artifact_type_from_manifest);
    let layer_types = parsed.as_ref().map(layer_media_types).unwrap_or_default();
    let kind = classify(
        reference,
        media_type,
        artifact_type.as_deref(),
        &layer_types,
        subject.is_some(),
    );
    let artifact_type = artifact_type.or_else(|| {
        kind.and_then(|kind| match kind {
            AccessoryKind::Signature => Some(COSIGN_SIMPLE_MEDIA_TYPE.to_string()),
            AccessoryKind::Attestation => Some(DSSE_ENVELOPE_MEDIA_TYPE.to_string()),
            AccessoryKind::Other => None,
        })
    });
    AccessoryMeta {
        kind,
        subject,
        artifact_type,
    }
}

/// `true` if the reference is a `sha256:…` digest.
#[must_use]
pub fn is_digest_reference(value: &str) -> bool {
    value.to_ascii_lowercase().starts_with("sha256:")
}

/// `true` if the tag is a Cosign accessory (`.sig`, `.att`, `.sbom`).
#[must_use]
pub fn is_accessory_tag(reference: &str) -> bool {
    has_extension(reference, "sig")
        || has_extension(reference, "att")
        || has_extension(reference, "sbom")
}

/// `true` if the tag is specifically a Cosign signature (`.sig`).
#[must_use]
pub fn is_signature_tag(reference: &str) -> bool {
    has_extension(reference, "sig")
}

/// Hides blobs, digest-only refs, and accessories from the UI listing.
#[must_use]
pub fn should_hide_from_listing(name: &str, reference: &str, accessory: Option<&str>) -> bool {
    name == "_blob"
        || is_digest_reference(reference)
        || accessory.is_some()
        || is_accessory_tag(reference)
}

/// `true` if this accessory counts as a signature for the badge.
#[must_use]
pub fn is_signature_accessory(accessory: Option<&str>, reference: &str) -> bool {
    matches!(accessory, Some("signature")) || is_signature_tag(reference)
}

/// Signed subject: `subject` field or Cosign tag convention.
#[must_use]
pub fn signature_subject(subject: Option<&str>, reference: &str) -> Option<String> {
    subject
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(str::to_ascii_lowercase)
        .or_else(|| subject_from_tag(reference))
}

/// `true` if `digest` (`sha256:hex`) matches the artifact checksum.
#[must_use]
pub fn digest_matches_checksum(digest: &str, checksum: &str) -> bool {
    let expected = format!("sha256:{checksum}");
    digest.eq_ignore_ascii_case(&expected)
}

/// Extracts the subject digest from a `sha256-<hex>.sig` tag (or `.att` / `.sbom`).
#[must_use]
pub fn subject_from_tag(reference: &str) -> Option<String> {
    let lower = reference.trim().to_ascii_lowercase();
    let stem = lower
        .strip_suffix(".sig")
        .or_else(|| lower.strip_suffix(".att"))
        .or_else(|| lower.strip_suffix(".sbom"))?;
    let hex = stem.strip_prefix("sha256-")?;
    if hex.len() == 64 && hex.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        Some(format!("sha256:{hex}"))
    } else {
        None
    }
}

fn subject_from_manifest(value: &serde_json::Value) -> Option<String> {
    value
        .get("subject")
        .and_then(|subject| subject.get("digest"))
        .and_then(serde_json::Value::as_str)
        .map(str::trim)
        .filter(|digest| is_digest_reference(digest))
        .map(str::to_ascii_lowercase)
}

fn artifact_type_from_manifest(value: &serde_json::Value) -> Option<String> {
    value
        .get("artifactType")
        .and_then(serde_json::Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned)
        .or_else(|| {
            layer_media_types(value)
                .into_iter()
                .find(|media| is_known_accessory_media(media))
        })
}

fn layer_media_types(value: &serde_json::Value) -> Vec<String> {
    let mut types = Vec::new();
    for key in ["layers", "blobs"] {
        let Some(items) = value.get(key).and_then(serde_json::Value::as_array) else {
            continue;
        };
        for item in items {
            if let Some(media) = item
                .get("mediaType")
                .and_then(serde_json::Value::as_str)
                .map(str::trim)
                .filter(|value| !value.is_empty())
            {
                types.push(media.to_string());
            }
        }
    }
    types
}

fn classify(
    reference: &str,
    media_type: &str,
    artifact_type: Option<&str>,
    layer_types: &[String],
    has_subject: bool,
) -> Option<AccessoryKind> {
    if is_signature_media(media_type)
        || artifact_type.is_some_and(is_signature_media)
        || layer_types.iter().any(|media| is_signature_media(media))
        || is_signature_tag(reference)
    {
        return Some(AccessoryKind::Signature);
    }
    if is_attestation_media(media_type)
        || artifact_type.is_some_and(is_attestation_media)
        || layer_types.iter().any(|media| is_attestation_media(media))
        || has_extension(reference, "att")
    {
        return Some(AccessoryKind::Attestation);
    }
    if is_accessory_tag(reference) || has_subject {
        return Some(AccessoryKind::Other);
    }
    None
}

fn is_signature_media(media_type: &str) -> bool {
    matches!(
        media_type,
        COSIGN_SIMPLE_MEDIA_TYPE
            | NOTATION_MEDIA_TYPE
            | "application/vnd.dev.sigstore.bundle+json"
            | "application/vnd.dev.sigstore.bundle.v0.3+json"
    )
}

fn is_attestation_media(media_type: &str) -> bool {
    matches!(
        media_type,
        DSSE_ENVELOPE_MEDIA_TYPE | "application/vnd.in-toto+json"
    )
}

fn is_known_accessory_media(media_type: &str) -> bool {
    is_signature_media(media_type) || is_attestation_media(media_type)
}

fn has_extension(value: &str, extension: &str) -> bool {
    std::path::Path::new(value)
        .extension()
        .is_some_and(|ext| ext.eq_ignore_ascii_case(extension))
}

/// Extracts payload digest and signature from a simple Cosign manifest.
#[must_use]
pub fn extract_simple_signature(manifest: &[u8]) -> Option<SimpleSignature> {
    let value = serde_json::from_slice::<serde_json::Value>(manifest).ok()?;
    let layers = value.get("layers")?.as_array()?;
    layers.iter().find_map(|layer| {
        let digest = layer
            .get("digest")
            .and_then(serde_json::Value::as_str)
            .map(str::trim)
            .filter(|digest| is_digest_reference(digest))?;
        let signature = layer
            .get("annotations")
            .and_then(|annotations| annotations.get(COSIGN_SIGNATURE_ANNOTATION))
            .and_then(serde_json::Value::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())?;
        Some(SimpleSignature {
            payload_digest: digest.to_ascii_lowercase(),
            signature_b64: signature.to_string(),
        })
    })
}

/// Subject digest declared in the simple-signing payload, if present.
#[must_use]
pub fn payload_subject_digest(payload: &[u8]) -> Option<String> {
    serde_json::from_slice::<serde_json::Value>(payload)
        .ok()?
        .pointer("/critical/image/docker-manifest-digest")
        .and_then(serde_json::Value::as_str)
        .map(str::trim)
        .filter(|digest| is_digest_reference(digest))
        .map(str::to_ascii_lowercase)
}

/// `true` if some PEM key verifies the signature over `payload`.
///
/// If the payload declares a digest and `subject` is passed, they must match.
#[must_use]
pub fn verify_simple(
    payload: &[u8],
    signature_b64: &str,
    keys_pem: &str,
    subject: Option<&str>,
) -> bool {
    if keys_pem.trim().is_empty() || payload.is_empty() {
        return false;
    }
    if let (Some(declared), Some(subject)) = (payload_subject_digest(payload), subject)
        && declared != subject.trim().to_ascii_lowercase()
    {
        return false;
    }
    let Some(signature) = decode_signature(signature_b64) else {
        return false;
    };
    parse_ecdsa_keys(keys_pem)
        .into_iter()
        .any(|key| verify_ecdsa(&key, payload, &signature))
}

fn decode_signature(value: &str) -> Option<Vec<u8>> {
    let compact: String = value.chars().filter(|ch| !ch.is_whitespace()).collect();
    STANDARD
        .decode(&compact)
        .or_else(|_| URL_SAFE.decode(&compact))
        .or_else(|_| URL_SAFE_NO_PAD.decode(&compact))
        .ok()
}

fn parse_ecdsa_keys(pem: &str) -> Vec<VerifyingKey> {
    split_pem_blocks(pem)
        .into_iter()
        .filter_map(|block| VerifyingKey::from_public_key_pem(&block).ok())
        .collect()
}

fn split_pem_blocks(pem: &str) -> Vec<String> {
    let mut blocks = Vec::new();
    let mut current = String::new();
    let mut inside = false;
    for line in pem.lines() {
        if line.contains("BEGIN") && line.contains("PUBLIC KEY") {
            inside = true;
            current.clear();
            current.push_str(line);
            current.push('\n');
            continue;
        }
        if inside {
            current.push_str(line);
            current.push('\n');
            if line.contains("END") && line.contains("PUBLIC KEY") {
                blocks.push(std::mem::take(&mut current));
                inside = false;
            }
        }
    }
    blocks
}

fn verify_ecdsa(key: &VerifyingKey, payload: &[u8], signature: &[u8]) -> bool {
    if let Ok(parsed) = Signature::from_der(signature)
        && key.verify(payload, &parsed).is_ok()
    {
        return true;
    }
    Signature::from_slice(signature)
        .ok()
        .is_some_and(|parsed| key.verify(payload, &parsed).is_ok())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn subject_from_classic_cosign_tag() {
        let digest = "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        let tag = digest.replacen(':', "-", 1) + ".sig";
        assert_eq!(subject_from_tag(&tag).as_deref(), Some(digest));
        assert!(is_signature_tag(&tag));
        assert!(should_hide_from_listing("demo", &tag, None));
    }

    #[test]
    fn inspects_referrer_manifest_with_subject() {
        let body = serde_json::json!({
            "schemaVersion": 2,
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "artifactType": COSIGN_SIMPLE_MEDIA_TYPE,
            "config": {
                "mediaType": "application/vnd.oci.empty.v1+json",
                "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
                "size": 2
            },
            "layers": [{
                "mediaType": COSIGN_SIMPLE_MEDIA_TYPE,
                "digest": "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
                "size": 32
            }],
            "subject": {
                "mediaType": "application/vnd.oci.image.manifest.v1+json",
                "digest": "sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
                "size": 100
            }
        });
        let meta = inspect(
            "sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
            "application/vnd.oci.image.manifest.v1+json",
            &serde_json::to_vec(&body).unwrap(),
        );
        assert_eq!(meta.kind, Some(AccessoryKind::Signature));
        assert_eq!(
            meta.subject.as_deref(),
            Some("sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc")
        );
        assert_eq!(
            meta.artifact_type.as_deref(),
            Some(COSIGN_SIMPLE_MEDIA_TYPE)
        );
    }

    #[test]
    fn regular_image_is_not_an_accessory() {
        let body = serde_json::json!({
            "schemaVersion": 2,
            "config": { "digest": "sha256:1" },
            "layers": [{ "digest": "sha256:2" }]
        });
        let meta = inspect(
            "latest",
            "application/vnd.oci.image.manifest.v1+json",
            &serde_json::to_vec(&body).unwrap(),
        );
        assert_eq!(meta.kind, None);
        assert_eq!(meta.subject, None);
    }

    #[test]
    fn digest_matches_artifact_checksum() {
        let checksum = "aa".repeat(32);
        assert!(digest_matches_checksum(
            &format!("sha256:{checksum}"),
            &checksum
        ));
        assert!(!digest_matches_checksum("sha256:deadbeef", &checksum));
    }

    #[test]
    fn verifies_a_p256_simple_signature() {
        use p256::ecdsa::SigningKey;
        use p256::ecdsa::signature::Signer;
        use p256::pkcs8::EncodePublicKey;

        let signing = SigningKey::random(&mut rand::rngs::OsRng);
        let pem = signing
            .verifying_key()
            .to_public_key_pem(p256::pkcs8::LineEnding::LF)
            .unwrap();
        let payload = br#"{"critical":{"image":{"docker-manifest-digest":"sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"},"type":"cosign container image signature"}}"#;
        let signature: Signature = signing.sign(payload);
        let encoded = STANDARD.encode(signature.to_der());
        let manifest = serde_json::json!({
            "layers": [{
                "mediaType": COSIGN_SIMPLE_MEDIA_TYPE,
                "digest": "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
                "annotations": { COSIGN_SIGNATURE_ANNOTATION: encoded }
            }]
        });
        let extracted = extract_simple_signature(&serde_json::to_vec(&manifest).unwrap()).unwrap();
        assert!(verify_simple(
            payload,
            &extracted.signature_b64,
            &pem,
            Some("sha256:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"),
        ));
        assert!(!verify_simple(
            payload,
            &extracted.signature_b64,
            &pem,
            Some("sha256:dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd")
        ));
        assert!(!verify_simple(payload, &extracted.signature_b64, "", None));
    }
}
